[tool.poetry]
name = "botw"
version = "0.1.0"
description = ""
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.12.1"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
black = "^19.10b0"
pre-commit = "^2.3.0"
flake8 = "^3.8.0"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
